2023-06-22 15:11:26,517 INFO: timeflag: <TimeFlag 1> [in D:\reservation_system\backend\app\routes.py:786]
2023-06-22 16:51:27,462 ERROR: Exception on /api/reservations [POST] [in C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 642, in add_reservation
    reservation = ReservationService.create_reservation(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 343, in create_reservation
    reservation_date = datetime.date.fromisoformat(reservation_date)  # convert to date object
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: ''
2023-06-22 16:51:29,011 ERROR: Exception on /api/reservations [POST] [in C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 642, in add_reservation
    reservation = ReservationService.create_reservation(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 343, in create_reservation
    reservation_date = datetime.date.fromisoformat(reservation_date)  # convert to date object
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: ''
2023-06-22 16:52:25,731 ERROR: Exception on /api/reservations [POST] [in C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 642, in add_reservation
    reservation = ReservationService.create_reservation(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 343, in create_reservation
    reservation_date = datetime.date.fromisoformat(reservation_date)  # convert to date object
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: ''
2023-06-22 16:53:05,425 ERROR: Exception on /api/reservations [POST] [in C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 642, in add_reservation
    reservation = ReservationService.create_reservation(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 343, in create_reservation
    reservation_date = datetime.date.fromisoformat(reservation_date)  # convert to date object
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: ''
2023-06-22 16:53:59,027 ERROR: Exception on /api/reservations [POST] [in C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hashino\AppData\Local\miniconda3\envs\reserve_system\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 642, in add_reservation
    reservation = ReservationService.create_reservation(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\reservation_system\backend\app\routes.py", line 343, in create_reservation
    reservation_date = datetime.date.fromisoformat(reservation_date)  # convert to date object
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: 'Wed, 21 Jun 2023 15:00:00 GM'
